#!/usr/bin/env vite-node
/**
 * scripts/generate-split-outputs.ts
 *
 * ⚠️  AUTO-GENERATED OUTPUTS — do not edit the files this script produces.
 *     Edit the source data at output/festival_brain_master.csv, then re-run:
 *     node_modules/.bin/vite-node scripts/generate-split-outputs.ts
 *
 * Reads:   output/festival_brain_master.csv  (canonical source of truth)
 * Writes:
 *   web/festivalBrain.ts         — TypeScript module for the website (no survival scripts)
 *   app/festivalSeed.json        — JSON seed for the companion app (no web-only display fields)
 *   src/data/festivalBrain.ts    — Live website copy (identical to web/festivalBrain.ts)
 *   output/festival-brain-validation.md — Validation report
 *
 * Field split:
 *   SHARED-CORE  slug · canonicalName · aliases · city · country
 *                startDate · endDate · latitude · longitude
 *                vibe · camping · expectedAttendance · primaryLanguage
 *                imageUrl · headliners · ticketUrlOfficial
 *
 *   WEB-ONLY     imageSource · imageLicence · lineupSourceUrl
 *                ticketUrlSkiddle · youtubeVideoId
 *
 *   APP-ONLY     medicalDoctorLocal · medicalAllergyLocal
 *                legalFreeToGoLocal · legalCallEmbassyLocal
 *                scriptLostSquad · scriptSubstance
 *                scriptMedicalTent · scriptCharging
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const CSV_PATH = path.join(ROOT, "output", "festival_brain_master.csv");

// ── Ensure output directories exist ───────────────────────────────────────────

const WEB_DIR = path.join(ROOT, "web");
const APP_DIR = path.join(ROOT, "app");
const OUT_DIR = path.join(ROOT, "output");

for (const dir of [WEB_DIR, APP_DIR, OUT_DIR]) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// ── CSV parser ─────────────────────────────────────────────────────────────────

function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQ && line[i + 1] === '"') { cur += '"'; i++; }
      else { inQ = !inQ; }
    } else if (ch === "," && !inQ) {
      out.push(cur); cur = "";
    } else { cur += ch; }
  }
  out.push(cur);
  return out;
}

function parseCsv(raw: string): Record<string, string>[] {
  const lines = raw.split(/\r?\n/).filter((l) => l.trim());
  const headers = splitCsvLine(lines[0]).map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const vals = splitCsvLine(line);
    const row: Record<string, string> = {};
    headers.forEach((h, i) => { row[h] = (vals[i] ?? "").trim(); });
    return row;
  });
}

// ── Field coercion ─────────────────────────────────────────────────────────────

function toNum(s: string): number | null {
  if (!s || s === "") return null;
  const n = parseFloat(s);
  return isNaN(n) ? null : n;
}

function toBool(s: string): boolean {
  return s.trim().toLowerCase() === "true";
}

function toStr(s: string): string {
  return s ?? "";
}

// ── Escape TypeScript template literal ────────────────────────────────────────

function q(s: string): string {
  return "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\${/g, "\\${") + "`";
}

// ── Columns to strip entirely (audit metadata, not data fields) ───────────────

const STRIP_COLS = new Set([
  "mergeConfidence_image",
  "mergeConfidence_headliners",
  "mergeConfidence_skiddle",
  "mergeConfidence_youtube",
  "mergeNotes",
]);

// ── Field sets ─────────────────────────────────────────────────────────────────

const SHARED_CORE_FIELDS = [
  "slug", "canonicalName", "aliases",
  "city", "country", "startDate", "endDate",
  "latitude", "longitude",
  "vibe", "camping", "expectedAttendance", "primaryLanguage",
  "imageUrl", "headliners", "ticketUrlOfficial",
] as const;

const WEB_ONLY_FIELDS = [
  "imageSource", "imageLicence", "lineupSourceUrl",
  "ticketUrlSkiddle", "youtubeVideoId",
] as const;

const APP_ONLY_FIELDS = [
  "medicalDoctorLocal", "medicalAllergyLocal",
  "legalFreeToGoLocal", "legalCallEmbassyLocal",
  "scriptLostSquad", "scriptSubstance",
  "scriptMedicalTent", "scriptCharging",
] as const;

// ── Web TypeScript generator ───────────────────────────────────────────────────

function generateWebTs(rows: Record<string, string>[], generatedAt: string): string {
  const lines: string[] = [];

  lines.push(`// ⚠️  AUTO-GENERATED — do not edit this file manually.`);
  lines.push(`//    Manual edits will be overwritten on the next build.`);
  lines.push(`//    Edit source: output/festival_brain_master.csv`);
  lines.push(`//    Re-generate: node_modules/.bin/vite-node scripts/generate-split-outputs.ts`);
  lines.push(`//    Generated: ${generatedAt}`);
  lines.push(``);
  lines.push(`// ─── Types ────────────────────────────────────────────────────────────────────`);
  lines.push(``);
  lines.push(`/** Shared-core fields present in both web and app builds. */`);
  lines.push(`export interface FestivalBrainCore {`);
  lines.push(`  /** URL slug — primary lookup key across all data layers */`);
  lines.push(`  slug: string;`);
  lines.push(`  /** Canonical display name */`);
  lines.push(`  canonicalName: string;`);
  lines.push(`  /** Space + pipe + space separated alternative names e.g. "EXIT Festival | Exit Fest" */`);
  lines.push(`  aliases: string;`);
  lines.push(`  city: string;`);
  lines.push(`  country: string;`);
  lines.push(`  /** ISO 8601 YYYY-MM-DD */`);
  lines.push(`  startDate: string;`);
  lines.push(`  /** ISO 8601 YYYY-MM-DD */`);
  lines.push(`  endDate: string;`);
  lines.push(`  latitude: number | null;`);
  lines.push(`  longitude: number | null;`);
  lines.push(`  /** Genre / energy descriptor e.g. "Techno / House" */`);
  lines.push(`  vibe: string;`);
  lines.push(`  camping: boolean;`);
  lines.push(`  expectedAttendance: number | null;`);
  lines.push(`  primaryLanguage: string;`);
  lines.push(`  imageUrl: string;`);
  lines.push(`  /** Comma-separated headliner names, or "TBA" */`);
  lines.push(`  headliners: string;`);
  lines.push(`  /** Primary CTA — official festival or third-party ticket URL (not Skiddle) */`);
  lines.push(`  ticketUrlOfficial: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/** Web-only fields — not exported to the app. */`);
  lines.push(`export interface FestivalBrain extends FestivalBrainCore {`);
  lines.push(`  /** Photo credit source name */`);
  lines.push(`  imageSource: string;`);
  lines.push(`  /** Licence string e.g. "CC0", "CC BY 2.0", "Official Media" */`);
  lines.push(`  imageLicence: string;`);
  lines.push(`  /** URL to full lineup announcement or festival programme */`);
  lines.push(`  lineupSourceUrl: string;`);
  lines.push(`  /** Skiddle affiliate URL — includes ?sktag=15628 */`);
  lines.push(`  ticketUrlSkiddle: string;`);
  lines.push(`  /** YouTube video ID for the hero embed (11 chars) — empty string if none */`);
  lines.push(`  youtubeVideoId: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`// ─── Data ────────────────────────────────────────────────────────────────────`);
  lines.push(``);
  lines.push(`export const festivalBrain: FestivalBrain[] = [`);

  for (const row of rows) {
    if (!row.slug) continue;

    lines.push(`  {`);
    // Shared-core
    lines.push(`    slug: ${q(toStr(row.slug))},`);
    lines.push(`    canonicalName: ${q(toStr(row.canonicalName))},`);
    lines.push(`    aliases: ${q(toStr(row.aliases))},`);
    lines.push(`    city: ${q(toStr(row.city))},`);
    lines.push(`    country: ${q(toStr(row.country))},`);
    lines.push(`    startDate: ${q(toStr(row.startDate))},`);
    lines.push(`    endDate: ${q(toStr(row.endDate))},`);
    lines.push(`    latitude: ${toNum(row.latitude) ?? "null"},`);
    lines.push(`    longitude: ${toNum(row.longitude) ?? "null"},`);
    lines.push(`    vibe: ${q(toStr(row.vibe))},`);
    lines.push(`    camping: ${toBool(row.camping)},`);
    lines.push(`    expectedAttendance: ${toNum(row.expectedAttendance) ?? "null"},`);
    lines.push(`    primaryLanguage: ${q(toStr(row.primaryLanguage))},`);
    lines.push(`    imageUrl: ${q(toStr(row.imageUrl))},`);
    lines.push(`    headliners: ${q(toStr(row.headliners))},`);
    lines.push(`    ticketUrlOfficial: ${q(toStr(row.ticketUrlOfficial))},`);
    // Web-only
    lines.push(`    imageSource: ${q(toStr(row.imageSource))},`);
    lines.push(`    imageLicence: ${q(toStr(row.imageLicence))},`);
    lines.push(`    lineupSourceUrl: ${q(toStr(row.lineupSourceUrl))},`);
    lines.push(`    ticketUrlSkiddle: ${q(toStr(row.ticketUrlSkiddle))},`);
    lines.push(`    youtubeVideoId: ${q(toStr(row.youtubeVideoId))},`);
    lines.push(`  },`);
  }

  lines.push(`];`);
  lines.push(``);
  lines.push(`// ─── Lookup helpers ──────────────────────────────────────────────────────────`);
  lines.push(``);
  lines.push(`/** Look up a festival by its canonical slug. */`);
  lines.push(`export function getFestivalBySlug(slug: string): FestivalBrain | undefined {`);
  lines.push(`  return festivalBrain.find((f) => f.slug === slug);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Look up by slug OR any pipe-separated alias.`);
  lines.push(` * Use when resolving legacy slugs that may differ from the canonical slug.`);
  lines.push(` */`);
  lines.push(`export function getFestivalBySlugOrAlias(slug: string): FestivalBrain | undefined {`);
  lines.push(`  return festivalBrain.find(`);
  lines.push(`    (f) =>`);
  lines.push(`      f.slug === slug ||`);
  lines.push(`      f.aliases.split(" | ").some((a) => a.trim().toLowerCase() === slug.toLowerCase())`);
  lines.push(`  );`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/** True if the festival has at least one purchasable ticket URL. */`);
  lines.push(`export function hasTicketUrl(f: FestivalBrain): boolean {`);
  lines.push(`  return !!(f.ticketUrlOfficial || f.ticketUrlSkiddle);`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

// ── App JSON generator ─────────────────────────────────────────────────────────

interface AppEntry {
  slug: string;
  canonicalName: string;
  aliases: string;
  city: string;
  country: string;
  startDate: string;
  endDate: string;
  latitude: number | null;
  longitude: number | null;
  vibe: string;
  camping: boolean;
  expectedAttendance: number | null;
  primaryLanguage: string;
  imageUrl: string;
  headliners: string;
  ticketUrlOfficial: string;
  survival: {
    medicalDoctorLocal: string;
    medicalAllergyLocal: string;
    legalFreeToGoLocal: string;
    legalCallEmbassyLocal: string;
    scriptLostSquad: string;
    scriptSubstance: string;
    scriptMedicalTent: string;
    scriptCharging: string;
  };
}

function generateAppJson(rows: Record<string, string>[], generatedAt: string): string {
  const entries: AppEntry[] = rows
    .filter((row) => row.slug)
    .map((row) => ({
      // Shared-core
      slug: toStr(row.slug),
      canonicalName: toStr(row.canonicalName),
      aliases: toStr(row.aliases),
      city: toStr(row.city),
      country: toStr(row.country),
      startDate: toStr(row.startDate),
      endDate: toStr(row.endDate),
      latitude: toNum(row.latitude),
      longitude: toNum(row.longitude),
      vibe: toStr(row.vibe),
      camping: toBool(row.camping),
      expectedAttendance: toNum(row.expectedAttendance),
      primaryLanguage: toStr(row.primaryLanguage),
      imageUrl: toStr(row.imageUrl),
      headliners: toStr(row.headliners),
      ticketUrlOfficial: toStr(row.ticketUrlOfficial),
      // App-only survival scripts (nested for clear separation)
      survival: {
        medicalDoctorLocal: toStr(row.medicalDoctorLocal),
        medicalAllergyLocal: toStr(row.medicalAllergyLocal),
        legalFreeToGoLocal: toStr(row.legalFreeToGoLocal),
        legalCallEmbassyLocal: toStr(row.legalCallEmbassyLocal),
        scriptLostSquad: toStr(row.scriptLostSquad),
        scriptSubstance: toStr(row.scriptSubstance),
        scriptMedicalTent: toStr(row.scriptMedicalTent),
        scriptCharging: toStr(row.scriptCharging),
      },
    }));

  const wrapper = {
    _generated: generatedAt,
    _source: "output/festival_brain_master.csv",
    _warning: "AUTO-GENERATED — do not edit this file manually. Manual edits will be overwritten. Edit the CSV source and re-run scripts/generate-split-outputs.ts",
    _fieldSplit: {
      sharedCore: [...SHARED_CORE_FIELDS],
      appOnly: [...APP_ONLY_FIELDS],
      webOnlyOmitted: [...WEB_ONLY_FIELDS],
    },
    count: entries.length,
    festivals: entries,
  };

  return JSON.stringify(wrapper, null, 2);
}

// ── Validation report generator ────────────────────────────────────────────────

// content.ts festival slugs (hard-coded from audit — update if content.ts changes)
const CONTENT_TS_SLUGS = new Set([
  "tomorrowland", "creamfields", "terminal-v", "edc-las-vegas", "ultra-europe",
  "latitude-festival", "boomtown-fair", "hospitality-in-the-park", "sonus-croatia",
  "defected-croatia", "kappa-futurefestival", "exit-serbia", "dimensions-croatia",
  "mystic-garden-amsterdam", "movement-detroit", "time-warp-mannheim",
  "suncebeat-new-horizons", "goodlife-festival", "mint-festival",
  "love-international", "dimensions-festival", "electric-love-festival",
  "primavera-sound", "ultra-miami", "sziget", "night-horizon",
  "untold-festival", "first-international-festival",
]);

// Fields required by the canonical schema spec
const REQUIRED_FIELDS: (keyof Record<string, string>)[] = [
  "slug", "canonicalName", "startDate", "endDate",
  "city", "country", "latitude", "longitude",
  "ticketUrlOfficial", "ticketUrlSkiddle", "youtubeVideoId",
];

// Fields absent from schema entirely (noted for future schema update)
const SCHEMA_LEVEL_GAPS = ["sourceOfficial", "lastVerifiedAt"];

function generateValidationReport(
  rows: Record<string, string>[],
  generatedAt: string
): string {
  const dataRows = rows.filter((r) => r.slug);
  const brainSlugs = dataRows.map((r) => r.slug);
  const brainSlugSet = new Set(brainSlugs);

  // ── 1. Duplicate slugs ─────────────────────────────────────────────────────
  const slugCounts: Record<string, number> = {};
  for (const s of brainSlugs) slugCounts[s] = (slugCounts[s] || 0) + 1;
  const duplicates = Object.entries(slugCounts).filter(([, c]) => c > 1);

  // ── 2. Missing required fields ─────────────────────────────────────────────
  type FieldGap = { slug: string; canonicalName: string; missingFields: string[] };
  const fieldGaps: FieldGap[] = [];
  for (const row of dataRows) {
    const missing = REQUIRED_FIELDS.filter((f) => !row[f] || row[f] === "");
    if (missing.length > 0) {
      fieldGaps.push({
        slug: row.slug,
        canonicalName: row.canonicalName,
        missingFields: missing,
      });
    }
  }

  // ── 3. Routes with no matching brain festival ──────────────────────────────
  // content.ts slugs that don't exist in festivalBrain → brain lookup returns undefined
  const contentSlugsWithNoBrain: string[] = [...CONTENT_TS_SLUGS].filter(
    (s) => !brainSlugSet.has(s)
  );

  // ── 4. Brain festivals with no content.ts entry ────────────────────────────
  // These fall through to CsvFestivalDetailLayout (acceptable, not an error)
  const brainSlugsWithNoContent: string[] = brainSlugs.filter(
    (s) => !CONTENT_TS_SLUGS.has(s)
  );

  // ── 5. Ticket coverage ─────────────────────────────────────────────────────
  const noTicketAtAll = dataRows.filter(
    (r) => !r.ticketUrlOfficial && !r.ticketUrlSkiddle
  );
  const noOfficialTicket = dataRows.filter((r) => !r.ticketUrlOfficial);
  const noSkiddleTicket = dataRows.filter((r) => !r.ticketUrlSkiddle);
  const noVideo = dataRows.filter((r) => !r.youtubeVideoId);
  const headlinersTBA = dataRows.filter(
    (r) => !r.headliners || r.headliners === "TBA"
  );

  // ── 6. Imminent events ─────────────────────────────────────────────────────
  const today = new Date("2026-04-03");
  const imminentCutoff = new Date("2026-05-03"); // 30 days
  const imminentEvents = dataRows.filter((r) => {
    const d = new Date(r.startDate);
    return d >= today && d <= imminentCutoff;
  });
  const pastEvents = dataRows.filter((r) => {
    const d = new Date(r.endDate);
    return d < today;
  });

  // ── Build report ───────────────────────────────────────────────────────────

  const lines: string[] = [];

  lines.push(`# Festival Brain — Validation Report`);
  lines.push(`Generated: ${generatedAt}`);
  lines.push(`Source: \`output/festival_brain_master.csv\``);
  lines.push(``);

  // Overview
  lines.push(`## Overview`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total festivals in brain | **${dataRows.length}** |`);
  lines.push(`| Duplicate slugs | **${duplicates.length}** |`);
  lines.push(`| Festivals with missing required fields | **${fieldGaps.length}** |`);
  lines.push(`| content.ts slugs with no brain match | **${contentSlugsWithNoBrain.length}** |`);
  lines.push(`| Brain slugs with no content.ts entry | **${brainSlugsWithNoContent.length}** |`);
  lines.push(`| No ticket URL at all | **${noTicketAtAll.length}** |`);
  lines.push(`| Missing youtubeVideoId | **${noVideo.length}** |`);
  lines.push(`| Headliners TBA | **${headlinersTBA.length}** |`);
  lines.push(`| Events within 30 days (imminent) | **${imminentEvents.length}** |`);
  lines.push(`| Events already past | **${pastEvents.length}** |`);
  lines.push(``);

  // Schema-level gaps
  lines.push(`## Schema-Level Gaps`);
  lines.push(``);
  lines.push(`These fields are **required by the canonical schema spec but do not exist`);
  lines.push(`in the current \`FestivalBrain\` interface or CSV**. They affect all ${dataRows.length} festivals.`);
  lines.push(``);
  for (const f of SCHEMA_LEVEL_GAPS) {
    lines.push(`- \`${f}\` — not in CSV, not in TypeScript interface`);
  }
  lines.push(``);
  lines.push(`**Action required:** Add these fields to the CSV and re-run the build before`);
  lines.push(`populating them via the research prompts in \`output/festival-brain-research-prompts.md\`.`);
  lines.push(``);

  // Duplicate slugs
  lines.push(`## Duplicate Slugs`);
  lines.push(``);
  if (duplicates.length === 0) {
    lines.push(`✅ None — all slugs are unique.`);
  } else {
    lines.push(`⚠️ The following slugs appear more than once in the brain dataset:`);
    lines.push(``);
    for (const [slug, count] of duplicates) {
      lines.push(`- \`${slug}\` — appears **${count} times**`);
    }
  }
  lines.push(``);

  // Missing required fields
  lines.push(`## Missing Required Fields`);
  lines.push(``);
  if (fieldGaps.length === 0) {
    lines.push(`✅ All festivals have every required field populated.`);
  } else {
    lines.push(`The following ${fieldGaps.length} festivals are missing one or more required fields:`);
    lines.push(``);
    lines.push(`| Festival | Slug | Missing Fields |`);
    lines.push(`|----------|------|----------------|`);
    for (const gap of fieldGaps) {
      lines.push(`| ${gap.canonicalName} | \`${gap.slug}\` | \`${gap.missingFields.join("\`, \`")}\` |`);
    }
  }
  lines.push(``);

  // Routes with no brain match
  lines.push(`## content.ts Slugs with No Brain Match`);
  lines.push(``);
  lines.push(`These festivals exist in \`src/data/content.ts\` but their slug does not match`);
  lines.push(`any entry in \`festivalBrain\`. The detail page will render with no headliners,`);
  lines.push(`no ticket URL, and no YouTube embed from the brain layer.`);
  lines.push(``);
  if (contentSlugsWithNoBrain.length === 0) {
    lines.push(`✅ All content.ts slugs have a matching brain entry.`);
  } else {
    for (const s of contentSlugsWithNoBrain) {
      // Try to find closest brain match
      const brainMatch = brainSlugs.find((b) => b.includes(s.split("-")[0]) || s.includes(b.split("-")[0]));
      lines.push(`- \`${s}\`${brainMatch ? ` — closest brain slug: \`${brainMatch}\`` : " — no close match found"}`);
    }
    lines.push(``);
    lines.push(`**Fix:** Update the slug in \`content.ts\` to match the brain slug, then add a`);
    lines.push(`redirect if the old URL was publicly indexed.`);
  }
  lines.push(``);

  // Brain slugs with no content entry
  lines.push(`## Brain Festivals with No content.ts Entry`);
  lines.push(``);
  lines.push(`These ${brainSlugsWithNoContent.length} brain festivals have no rich editorial entry in \`content.ts\`.`);
  lines.push(`They render via \`CsvFestivalDetailLayout\` as CSV-tier pages. This is expected`);
  lines.push(`for non-featured festivals but listed here for completeness.`);
  lines.push(``);
  lines.push(`<details>`);
  lines.push(`<summary>Show ${brainSlugsWithNoContent.length} CSV-tier brain festivals</summary>`);
  lines.push(``);
  for (const s of brainSlugsWithNoContent) {
    const row = dataRows.find((r) => r.slug === s);
    lines.push(`- \`${s}\` — ${row?.canonicalName ?? ""}`);
  }
  lines.push(``);
  lines.push(`</details>`);
  lines.push(``);

  // Ticket coverage
  lines.push(`## Ticket URL Coverage`);
  lines.push(``);
  lines.push(`### No ticket URL at all (official OR Skiddle) — ${noTicketAtAll.length} festivals`);
  if (noTicketAtAll.length === 0) {
    lines.push(`✅ All festivals have at least one ticket URL.`);
  } else {
    for (const r of noTicketAtAll) {
      lines.push(`- \`${r.slug}\` — ${r.canonicalName}`);
    }
  }
  lines.push(``);
  lines.push(`### Missing \`ticketUrlOfficial\` — ${noOfficialTicket.length} festivals`);
  for (const r of noOfficialTicket) {
    const hasSkiddle = !!r.ticketUrlSkiddle;
    lines.push(`- \`${r.slug}\` — ${r.canonicalName}${hasSkiddle ? " _(Skiddle only)_" : " ⚠️ no ticket URL"}`);
  }
  lines.push(``);
  lines.push(`### Missing \`ticketUrlSkiddle\` — ${noSkiddleTicket.length} festivals`);
  lines.push(`_(includes non-UK festivals Skiddle does not cover — not all are fixable)_`);
  lines.push(``);
  for (const r of noSkiddleTicket) {
    lines.push(`- \`${r.slug}\` — ${r.canonicalName} (${r.country})`);
  }
  lines.push(``);

  // Video coverage
  lines.push(`## YouTube Video Coverage`);
  lines.push(``);
  lines.push(`${noVideo.length} festivals have no \`youtubeVideoId\` — their hero section will show no video:`);
  lines.push(``);
  for (const r of noVideo) {
    lines.push(`- \`${r.slug}\` — ${r.canonicalName}`);
  }
  lines.push(``);

  // Headliners
  lines.push(`## Headliner Status`);
  lines.push(``);
  lines.push(`${headlinersTBA.length} festivals have headliners listed as \`TBA\` or blank:`);
  lines.push(``);
  for (const r of headlinersTBA) {
    lines.push(`- \`${r.slug}\` — ${r.canonicalName} (${r.startDate})`);
  }
  lines.push(``);

  // Imminent + past events
  lines.push(`## Imminent Events (within 30 days of ${generatedAt.split("T")[0]})`);
  lines.push(``);
  if (imminentEvents.length === 0) {
    lines.push(`_No events within 30 days._`);
  } else {
    lines.push(`⚠️ These festivals start soon — verify ticket URLs and headliners are current:`);
    lines.push(``);
    for (const r of imminentEvents) {
      const hasTicket = !!(r.ticketUrlOfficial || r.ticketUrlSkiddle);
      lines.push(`- \`${r.slug}\` — ${r.canonicalName}, **${r.startDate}**${!hasTicket ? " — ⚠️ NO TICKET URL" : ""}`);
    }
  }
  lines.push(``);
  lines.push(`## Past Events`);
  lines.push(``);
  if (pastEvents.length === 0) {
    lines.push(`_No past events in the dataset._`);
  } else {
    lines.push(`These events have an \`endDate\` before today. Consider archiving or updating to 2027 dates:`);
    lines.push(``);
    for (const r of pastEvents) {
      lines.push(`- \`${r.slug}\` — ${r.canonicalName} ended ${r.endDate}`);
    }
  }
  lines.push(``);

  // Output manifest
  lines.push(`## Output Files Generated`);
  lines.push(``);
  lines.push(`| File | Purpose |`);
  lines.push(`|------|---------|`);
  lines.push(`| \`web/festivalBrain.ts\` | TypeScript module for the website — no survival scripts |`);
  lines.push(`| \`src/data/festivalBrain.ts\` | Live copy of web/festivalBrain.ts — consumed by Vite |`);
  lines.push(`| \`app/festivalSeed.json\` | JSON seed for the companion app — no web-only display fields |`);
  lines.push(`| \`output/festival-brain-validation.md\` | This report |`);
  lines.push(``);
  lines.push(`## Field Split Applied`);
  lines.push(``);
  lines.push(`| Bucket | Fields |`);
  lines.push(`|--------|--------|`);
  lines.push(`| **Shared-core** (web + app) | \`${SHARED_CORE_FIELDS.join("\`, \`")}\` |`);
  lines.push(`| **Web-only** (web TS only) | \`${WEB_ONLY_FIELDS.join("\`, \`")}\` |`);
  lines.push(`| **App-only** (app JSON only, nested under \`survival\`) | \`${APP_ONLY_FIELDS.join("\`, \`")}\` |`);
  lines.push(``);

  return lines.join("\n");
}

// ── Main ───────────────────────────────────────────────────────────────────────

function main() {
  if (!fs.existsSync(CSV_PATH)) {
    console.error(`\n❌ Source file not found: ${CSV_PATH}`);
    console.error(`   Run scripts/build-festival-brain.ts first.\n`);
    process.exit(1);
  }

  const raw = fs.readFileSync(CSV_PATH, "utf-8");
  const allRows = parseCsv(raw);
  // Strip audit-only columns
  const rows = allRows.map((row) => {
    const clean: Record<string, string> = {};
    for (const [k, v] of Object.entries(row)) {
      if (!STRIP_COLS.has(k)) clean[k] = v;
    }
    return clean;
  });

  const dataRows = rows.filter((r) => r.slug);
  const generatedAt = new Date().toISOString();

  // ── Write web TypeScript ───────────────────────────────────────────────────

  const webTs = generateWebTs(rows, generatedAt);
  const WEB_TS_PATH = path.join(WEB_DIR, "festivalBrain.ts");
  const SRC_TS_PATH = path.join(ROOT, "src", "data", "festivalBrain.ts");

  fs.writeFileSync(WEB_TS_PATH, webTs, "utf-8");
  fs.writeFileSync(SRC_TS_PATH, webTs, "utf-8");

  // ── Write app JSON ─────────────────────────────────────────────────────────

  const appJson = generateAppJson(rows, generatedAt);
  const APP_JSON_PATH = path.join(APP_DIR, "festivalSeed.json");
  fs.writeFileSync(APP_JSON_PATH, appJson, "utf-8");

  // ── Write validation report ────────────────────────────────────────────────

  const report = generateValidationReport(rows, generatedAt);
  const REPORT_PATH = path.join(OUT_DIR, "festival-brain-validation.md");
  fs.writeFileSync(REPORT_PATH, report, "utf-8");

  // ── Console summary ────────────────────────────────────────────────────────

  console.log(`\n✅ Festival Brain — split output complete`);
  console.log(`   Generated: ${generatedAt}`);
  console.log(`   Source:    ${CSV_PATH}`);
  console.log(`   Festivals: ${dataRows.length}`);
  console.log(`\n   Web TypeScript (no survival scripts):`);
  console.log(`   → ${WEB_TS_PATH}`);
  console.log(`   → ${SRC_TS_PATH} (live site copy)`);
  console.log(`\n   App JSON (shared-core + survival, no web-only fields):`);
  console.log(`   → ${APP_JSON_PATH}`);
  console.log(`\n   Validation report:`);
  console.log(`   → ${REPORT_PATH}\n`);
}

main();
